export const ADD_TICKET = 'ADD_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const UPDATE_TICKET_ISSUE = 'UPDATE_TICKET_ISSUE';
export const TOGGLE_IS_EDITING = 'TOGGLE_IS_EDITING';
export const REMOVE_SELECTED_TICKET = 'REMOVE_SELECTED_TICKET';
export const ADD_SELECTED_TICKET = 'ADD_SELECTED_TICKET';